### ISSUE TITLE
Tracking issue for IPv6 support 

### ISSUE THREAD

**Issue by icorderi** [GGist/ssdp-rs#18]
Search, notify and the server binding should work under IPv6.
Support for Link-local addresses is important.

**Comment by icorderi** [comment]
@GGist I'll be working on this on a [feature branch](https://github.com/icorderi/ssdp-rs/tree/feature/ipv6) in my fork. 

I can do a PR against master when I'm done, or I can push periodically against a local feature/ipv6 branch if you prefer that.

**Comment by GGist** [comment]
You can just make a PR against master when done.

Thanks for tackling this issue!
